config/routes.rb
Rails.application.routes.draw do
  get "/livestocks/feed" => 'livestocks#feed'
  get "/livestocks/admin" => 'livestocks#admin'
resources :livestocks

  root 'livestocks#index'
  

end

app/models/livestock.rb
class Livestock < ActiveRecord::Base
  has_attached_file :photo, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/jpg']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    #private
#def after_sign_out_path_for(resource_or_scope)
  #  'livestocks'
  #end
  #I need help with the above URL to redirect the user after signing out,
  #I want it to go to the main page but it goes to the root and makes me sign in.

end

app/controllers/livestocks_controller.rb
class LivestocksController < ApplicationController
  before_action :set_livestock, only: [:show, :edit, :update, :destroy]

  # GET /livestocks
  # GET /livestocks.json
  def index
  end

  # GET /livestocks/1
  # GET /livestocks/1.json
  def show
    @livestock = Livestock.find(params[:id])
  end

  def admin
    @livestocks = Livestock.all
  end

  def feed
    @livestocks = Livestock.all.page(params[:page]).per(5)
  end

  # GET /livestocks/new
  def new
    @livestock = Livestock.new
  end

  # GET /livestocks/1/edit
  def edit
  end

  # POST /livestocks
  # POST /livestocks.json
  def create
    @livestock = Livestock.new(livestock_params)
    respond_to do |format|
      if @livestock.save
        format.html { redirect_to @livestock, notice: 'Your animal was successfully submitted.' }
        format.json { render :show, status: :created, location: @livestock }
      else
        format.html { render :new }
        format.json { render json: @livestock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livestocks/1
  # PATCH/PUT /livestocks/1.json
  def update
    respond_to do |format|
      if @livestock.update(livestock_params)
        format.html { redirect_to @livestock, notice: 'Your animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @livestock }
      else
        format.html { render :edit }
        format.json { render json: @livestock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livestocks/1
  # DELETE /livestocks/1.json
  def destroy
    @livestock.destroy
    respond_to do |format|
      format.html { redirect_to livestocks_url, notice: 'Your animal was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livestock
      @livestock = Livestock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livestock_params
      params.require(:livestock).permit(:tag, :breed, :weight, :age, :grade, :gender, :delivery_date, :seller, :email, :phone, :location, :photo, :photo_file_name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/livestocks_helper.rb
module LivestocksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!-- <?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>http://localhost:3000</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration> -->

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Mifugo Trade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

<html lang="en">


  <style>

    .container {
      padding: 0px;
    }

    input {
      border-radius: 0px !important;
    }

    .container-fluid {
      padding: 0px;
    }

    .form-control {
      height: 70px;
      border-top: 0px;
    }

    .container-fluid .jumbotron {
      background-color: #60C356;
      border-radius: 0px;
      padding-bottom: 0px;
      margin-bottom: 0px;
    }

    .btn-primary {
      border-color: transparent;
      height: 61px;
      font-size: 20px;
      background-color: #39BAF1;
      opacity: 1;

    }

    .btn-primary:hover {
      border-color: transparent;
      height: 61px;
      font-size: 20px;
      background-color: #39BAF1;
      opacity: 0.9;
    }

    .image-upload {
      display: none !important;
    }

    .image-placeholder {
      height: 240px;
      background-color: #DDD;
      text-align: center;
      color: white;
      padding: 60px 0px;
      font-size: 20px;
      line-height: 24px;
      cursor: pointer;
    }

    .image-placeholder:hover {
      background-color: none !important;
    }

    .disclaimer {
      padding: 10px 20px;
      padding-top: 20px;
    }

    .success {
      background-color: #7DD077;
      height: 520px;
      text-align: center;
      color: white;
      padding: 180px 30px;
      font-size: 30px;
      line-height: 32px;
    }

    .success p {
      font-size: 20px;
      padding: 0px 40px;
    }

    .next-auction {
      background-color: #7DD077;
      height: 280px;
      text-align: center;
      color: white;
      padding: 50px 0px;
      font-size: 20px;
    }

    a:visited {
      color: #EFEFEF;
    }

    a {
      color: white;
    }

    a:hover {
      background-color: none !important;
      color: none !important;
    }

    .actions img:hover {
      background-color: none;
    }

    .upload_subtext {
      font-size: 14px;
      color: black;
    }

    th {
      padding: 10px;
    }


#livestock_age,
#livestock_gender,
#livestock_breed,
#livestock_grade
 {
  display: block;
  width: 100%;
  height: 70px;
  padding: 6px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
  -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
  transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
  border-top: 0px;
  }


</style>

app/views/livestocks/_form.html.erb
<style>

h2,p,h4 {
  font-family: "Avenir", Arial, Helvetica, sans-serif;
}

select {
  -o-appearance: none;
  -webkit-appearance:none;
  -moz-appearance: none;
}

</style>


<div class="actions">
    <div class="image-placeholder">
      <%=image_tag('white_cow.png')%><br/><br/>
      <b>Upload Image</b><br/>
      <div class="upload_subtext"></div>
    </div>

    <%= form_for @livestock, :html => {:multipart => true } do |form| %>
         <%= form.file_field :photo, :class => "image-upload"%>
         <!-- TAG -->
         <%= form.text_field :tag, :class => "form-control modal-input",    :placeholder => "Tag #"%>
         <!-- WEIGHT -->
         <%= form.text_field :weight, :class => "form-control modal-input",    :placeholder => "Live Weight (kg)"%>
         <!-- GRADE -->
         <%= form.select :grade, ["1", "2", "3","4","5" ], :prompt => 'Grade'%>
         <!-- BREED -->
         <%= form.select :breed, ["Zebu", "Sahiwal", "Boran","Mixed","Other" ], :prompt => 'Breed'%>
         <!-- AGE -->
          <%= form.select :age, ["0-1 Years", "1-2 Years", "2-3 Years","4-5 Years",">5 Years"], :prompt => 'Age'%>
          <!-- GENDER -->
          <%= form.select :gender, ["Male","Female"], :prompt => 'Gender'%>
         <%= form.text_field :delivery_date, :class => "form-control modal-input", :placeholder => "Delivery Date" %>
         <%= form.text_field :price, :class => "form-control modal-input",         :placeholder => "Price" %>
         <%= form.text_field :seller, :class => "form-control modal-input",        :placeholder => "Seller" %>
         <%= form.text_field :email, :class => "form-control modal-input",         :placeholder => "Email" %>
         <%= form.text_field :phone, :class => "form-control modal-input",         :placeholder => "Phone" %>
         <%= form.text_field :location, :class => "form-control modal-input",         :placeholder => "Sub-country" %>
         <%= form.submit 'Create', :class => "btn-primary step-one", :style => "width: 100%"%>
    <% end %>
  </div>
<script>


$(".image-placeholder").click(function(){
  $(".image-upload").click();
  $(".upload_subtext").text("Success! Click again to upload another photo.");
})

</script>

app/views/livestocks/admin.html.erb
<h1 style="margin-left: 20px;">Listed Animals</h1>

<style>

.leaderboard-container {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
}

.leaderboard-header,
.leaderboard-item {
  display: flex;
  flex-direction: row;
  justify-content: space-around;
  align-items: center;
  height: 70px;
  border-bottom: 1px solid #EFEFEF;
}

.leaderboard-header span {
  font-weight: bold;
}

.leaderboard-header span,
.leaderboard-item span {
  padding-left: 25px;
  display: inline-block;
  width: 100%;
  max-width: 120px;
}

.leaderboard-header .tag,
.leaderboard-item .tag {
  max-width: 80px;
}

.leaderboard-header .age,
.leaderboard-item .age {
  max-width: 120px;
}

.leaderboard-header .breed,
.leaderboard-item .breed {
  max-width: 100px;
}

.leaderboard-header .grade,
.leaderboard-item .grade {
  max-width: 80px;
}

.leaderboard-header .weight,
.leaderboard-item .weight{
  max-width: 100px;
}

.leaderboard-header .gender,
.leaderboard-item .gender{
  max-width: 100px;
}

.leaderboard-header .email,
.leaderboard-item .email{
  max-width: 200px;
}

.actions a{
  color: black !important;
}

</style>

<div class="leaderboard-container"> 
  <div class="leaderboard-header">
      <span class="tag">Tag #</span>
      <span class="age">Age</span>
      <span class="breed">Breed</span>
      <span class="grade">Grade</span>
      <span class="weight">Weight</span>
      <span class="gender">Gender</span>
      <span class="delivery_date">Delivery Date</span>
      <span class="price">Price</span>
      <span class="seller">Seller</span>
      <span class="email">Email</span>
      <span class="phone">Phone</span>
      <span class="location">Location</span>
      <span class="actions">Actions</span>
  </div>
  <% @livestocks.each do |livestock| %>
    <div class="leaderboard-item">
      <span class="tag"><%= livestock.tag %></span>
      <span class="age"><%= livestock.age %></span>
      <span class="breed"><%= livestock.breed %></span>
      <span class="grade"><%= livestock.weight %></span>
      <span class="weight"><%= livestock.grade %></span>
      <span class="gender"><%= livestock.gender %></span>
      <span class="delivery_date"><%= livestock.delivery_date %></span>
      <span class="price"><%= livestock.price %></span>
      <span class="seller"><%= livestock.seller %></span>
      <span class="email"><%= livestock.email %></span>
      <span class="phone"><%= livestock.phone %></span>
      <span class="location"><%= livestock.location %></span>
      <span class="actions">
        <%= link_to 'Edit', edit_livestock_path(livestock) %>
        <%= link_to 'Destroy', livestock, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  <% end %>
  <br/><br/>
  <span class="actions" style="margin-left: 20px; text-decoration: underline">
    <%= link_to 'New Livestock', new_livestock_path %>
  </span>
</div>

app/views/livestocks/edit.html.erb
<h1>Editing livestock</h1>

<%= render 'form' %>

<%= link_to 'Show', @livestock %> |
<%= link_to 'Back', livestocks_path %>

app/views/livestocks/feed.html.erb
<style>

.cow-container {
  width: 100%;
  padding: 40px;
}

.cow-container img {
  border-radius: 4px;
  margin: 0 auto;
  width: 100%;
  display: block;
  margin-bottom: 20px;
}

.feed-container {
  width: 100%;
  margin: 0 auto;
  display: block;
}

p {
  margin: 10px 0px;
  font-size: 16px;
  font-weight: normal;
  padding-right: 20px;
  display: inline !important;
}

a,
a:hover,
a:visited {
  color: white !important;
  text-decoration: none;
  background: none;
}

label {
  font-size: 16px;
  margin-left: 20px;
  padding-right: 5px;
}

h2,p {
  font-family: "Avenir", Arial, Helvetica, sans-serif;
}

h4 {
  font-family: "Avenir", Arial, Helvetica, sans-serif;
}

.cow-container:nth-child(odd) {
  background-color: #EFEFEF !important;
}

.btn-primary {
  height: 45px !important;
  color: white !important;
}

.pagination {
  margin-top: 40px;
  margin-bottom: 20px;
  padding-left: 30px;
}

.pagination span,
.pagination a {
  color: white !important;
  background-color: #39BAF1;
  padding: 10px;
  text-align: center;
  border-radius: 4px;
  margin: 0px 10px;
  width: 200px !important;
  font-family: "Avenir", Arial, Helvetica, sans-serif;
  font-size: 20px;
}

span.page {
  padding: 10px 0px;
  display: none;
}

span.page.current {
  background-color: black;
  padding: 10px 22px;
}

span.page.gap {
  padding: 10px 20px;
}

.last, 
.first {
  display: none;
}

</style>

<div class="container-fluid">
    <div class="jumbotron" style="padding: 10px">
        <h4 style="color: white; text-align: center">MIFUGO TRADE</h4>
    </div>

    <div class="feed-container">

      <% @livestocks.each do |livestock| %>
        <div class="cow-container">
          <h2>Tag #<%=livestock.tag%></h2>
          <img src="<%= livestock.photo %>"/>
          <span>
            <label style="margin-left: 0px">Breed</label>
            <p><%=livestock.breed%></p>
          </span>
          <span>
            <label style="margin-left: 0px">Grade</label>
            <p><%=livestock.grade%></p>
          </span>
          <span><br/><br/>
            <label style="margin-left: 0px">Weight</label>
            <p><%=livestock.weight%>kg</p>
          </span>
          <span>
            <label style="margin-left: 0px">Age</label>
            <p><%=livestock.age%></p>
          </span>
          <span><br/><br/>
            <label style="margin-left: 0px">Gender</label>
            <p><%=livestock.gender%></p>
          </span>
          <span>
            <label style="margin-left: 0px">Location</label>
            <p><%=livestock.location%></p>
          </span><br/><br/><br/>
          <%=link_to "View", livestock_path(livestock), :class => "btn btn-primary" %>
        </div>
      <% end %>

     <%=paginate @livestocks %>
    </div>
</div>

app/views/livestocks/index.html.erb
<style>

body {
  background: url("http://cdn1.editmysite.com/uploads/4/9/0/6/49061181/background-images/1347285720.jpg") no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.home-buttons {
  text-align: center;
  display: block;
}

.home-buttons a {
  vertical-align: middle;
  padding-top: 15px;
}

.home-container {
  padding-top: 300px;
}

h4 {
  font-family: "Avenir", Arial, Helvetica, sans-serif;
}

</style>

<div class="container-fluid">
    <div class="jumbotron" style="padding: 10px">
        <h4 style="color: white; text-align: center">MIFUGO TRADE</h4>
    </div>
    <div class="your-clock"></div>
    <div class="home-container">
      <div class="home-buttons">
        <%=link_to "SELLERS", new_livestock_path, id: 'new' , class: "btn btn-primary", style: "width: 290px; margin-bottom: 20px" %></br>
        <%=link_to "BUYERS", livestocks_feed_path, id: 'feed' , class: "btn btn-primary", style: "width: 290px; margin-bottom: 20px" %>
      </div>
    </div>
</div>

app/views/livestocks/new.html.erb
<div class="container-fluid">
   	<div class="jumbotron" style="padding: 10px">
        <a href="/">
        	<h4 style="color: white; text-align: center">Mifugo Trade</h4>
        </a>
    </div>
	<%= render 'form' %>
</div>

app/views/livestocks/show.html.erb
<style>

.cow-container {
  width: 100%;
  padding: 40px;
}

.cow-container:nth-child(even) {
  background-color: #EFEFEF !important;
}

.cow-container img {
  border-radius: 4px;
  margin: 0 auto;
  width: 100%;
  display: block;
  margin-bottom: 20px;
}

.feed-container {
  width: 100%;
  margin: 0 auto;
  display: block;
}

p {
  margin: 10px 0px;
  font-size: 16px;
  font-weight: normal;
}

a {
  color: white !important;
  text-decoration: none;
}

label {
  font-size: 16px;
}

h2,p,h4 {
  font-family: "Avenir", Arial, Helvetica, sans-serif;
}

.btn-primary {
  height: 45px !important;
  color: white !important;
}


</style>




<div class="container-fluid">
   	<div class="jumbotron" style="padding: 10px">
        <h4 style="color: white; text-align: center">Mifugo Trade</h4>
    </div>
</div>


<div class="feed-container">
    <div class="cow-container">
      <h2>Tag #<%=@livestock.tag%></h2>
      <img src="<%=@livestock.photo %>"/>
      <span>
        <label>Breed</label>
        <p><%=@livestock.breed%></p>
      </span>
      <span>
        <label>Grade</label>
        <p><%=@livestock.grade%></p>
      </span>
      <span>
        <label>Weight</label>
        <p><%=@livestock.weight%>kg</p>
      </span>
      <span>
        <label>Age</label>
        <p><%=@livestock.age%> Years Old</p>
      </span>
      <span>
        <label>Gender</label>
        <p><%=@livestock.gender%></p>
      </span>
      <span>
        <label>Location</label>
        <p><%=@livestock.location%></p>
      </span>
      <br/><span>
      <%=link_to "Back",livestocks_feed_path, id: 'feed', :class => "btn btn-primary"%>
     </span>
    </div>
</div>

app/views/submission/admin_livestock_submission.erb
[ADMIN COPY]<br/><br/>

<b>Success!</b> You have submitted an animal for sale to the Rangeland Auction marketplace. Our first auction will be on 4/10/2015, we will contact you with further details. Please feel free to reach out with any questions or concerns.<br/><br/>

Thanks,<br/>
Mifugo Trade Team
<br/><br/>

<b>Submission Details</b><br/>
Tag: <%= @livestock.tag %><br/>
Weight: <%= @livestock.weight %><br/>
Grade: <%= @livestock.grade %><br/>
Breed: <%= @livestock.breed %><br/>
Age: <%= @livestock.age %><br/>
Gender: <%= @livestock.gender %><br/>
Earliest Delivery Date: <%= @livestock.delivery_date %><br/>
Reserve Price: <%=number_to_currency(@livestock.price) %><br/>
Seller: <%= @livestock.seller %><br/>
Email: <%= @livestock.phone %><br/>
Location: <%= @livestock.location %><br/>
Photos: Successfully Uploaded!

app/views/submission/livestock_submission.erb
<b>Success!</b> You have submitted an animal for sale to the Rangeland Auction marketplace. Our first auction will be on 4/10/2015, we will contact you with further details. Please feel free to reach out with any questions or concerns.<br/><br/>

Thanks,<br/>
Mifugo Trade Team
<br/><br/>

<b>Submission Details</b><br/>
Tag: <%= @livestock.tag %><br/>
Weight: <%= @livestock.weight %><br/>
Grade: <%= @livestock.grade %><br/>
Breed: <%= @livestock.breed %><br/>
Age: <%= @livestock.age %><br/>
Gender: <%= @livestock.gender %><br/>
Earliest Delivery Date: <%= @livestock.delivery_date %><br/>
Reserve Price: <%=number_to_currency(@livestock.price) %><br/>
Seller: <%= @livestock.seller %><br/>
Email: <%= @livestock.phone %><br/>
Location: <%= @livestock.location %><br/>
Photos: Successfully Uploaded!